# Generated by Django 5.2.7 on 2026-01-11 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('processing_days', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarangayStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('captain', 'Barangay Captain'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('clerk', 'Barangay Clerk'), ('staff', 'Barangay Staff')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='resident_ids/', verbose_name='Valid ID Photo')),
                ('verification_status', models.CharField(choices=[('pending', '⏳ Pending Review'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes for verification')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('under_review', '📋 Under Review'), ('approved', '✅ Approved'), ('ready', '📄 Ready for Pickup'), ('completed', '🎉 Completed'), ('rejected', '❌ Rejected')], default='pending', max_length=20)),
                ('purpose', models.TextField()),
                ('resident_age', models.IntegerField(blank=True, null=True)),
                ('resident_address', models.TextField(blank=True, null=True)),
                ('years_in_residence', models.IntegerField(default=0)),
                ('months_in_residence', models.IntegerField(default=0)),
                ('community_tax_cert_no', models.CharField(blank=True, max_length=100)),
                ('ctc_issued_on', models.DateField(blank=True, null=True)),
                ('ctc_issued_at', models.CharField(blank=True, max_length=200)),
                ('or_number', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('verification_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORCEP.servicetype')),
            ],
        ),
    ]
