# Generated by Django 5.2.7 on 2026-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORCEP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_requests', models.IntegerField(default=0)),
                ('approved_requests', models.IntegerField(default=0)),
                ('completed_requests', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
