# Generated by Django 5.2.7 on 2026-05-07 14:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORCEP', '0003_servicerequest_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangaystaff',
            options={'verbose_name': 'Barangay Staff', 'verbose_name_plural': 'Barangay Staff'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='monthlystatistics',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Monthly Statistics', 'verbose_name_plural': 'Monthly Statistics'},
        ),
        migrations.AlterModelOptions(
            name='residentprofile',
            options={'verbose_name': 'Resident Profile', 'verbose_name_plural': 'Resident Profiles'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-date_requested'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 7, 14, 43, 22, 836896, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ORCEP.servicetype'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
